#!/usr/bin/env bash

# Distributed copy of a directory into an iRODS collection
# Christopher Harrison <ch12@sanger.ac.uk>

set -euo pipefail

BINARY="$(readlink -fn "$0")"
PROGNAME="$(basename "${BINARY}")"

# Maximum number of concurrent iputs
export IPUT_LIMIT="${IPUT_LIMIT-30}"

# Maximum number of elements in job array
export BSUB_LIMIT="${BSUB_LIMIT-300}"

stderr() {
  local message="$*"

  if [[ -t 2 ]]; then
    message="\033[0;31m${message}\033[0m"
  fi

  >&2 echo -e "${message}"
}

usage() {
  cat <<-EOF
	Usage: ${PROGNAME} /your/source/directory /the/irods/collection
	EOF
}

main() {
  local mode="$1"

  case "${mode}" in
    "__setup")
      local source_dir="$1"
      local dest_coll="$2"

      strip_prefix() {
        # Strip the source directory prefixed to source files
        local data="$1"
        echo "${data#${source_dir}/}"
      }

      get_manifest() {
        # Find files of a given type in the source directory, excluding
        # the .imirror directory we created for keeping state
        # FIXME This will break horribly for files with \n in their names
        local type="$1"
        find "${source_dir}" \
             -mindepth 1 \
             -path "${source_dir}/.imirror" -prune \
             -o -type "${type}" -print
      }

      # Generate manifest
      echo "Generating manifest..."
      local manifest_dir="${source_dir}/.imirror/manifest"
      mkdir -p "${manifest_dir}"
      get_manifest d > "${manifest_dir}/dirs"
      get_manifest f | split -dn "r/${BSUB_LIMIT}" - "${manifest_dir}/files."

      # Create subcollections
      echo "Mirroring directory structure on iRODS..."
      local subdir
      local subcoll
      while IFS= read -r subdir; do
        subcoll="${dest_coll}/$(strip_prefix "${subdir}")"
        imkdir -p "${subcoll}"
      done < "${manifest_dir}/dirs"

      # TODO Distributed iput job
      ;;

    "__copy")
      # TODO
      ;;

    *)
      if ! (( $# == 2 )); then
        stderr "Invalid arguments!"
        usage
        exit 1
      fi

      local source_dir="$(readlink -fn "$1")"
      local dest_coll="$2"

      if ! [[ -d "${source_dir}" ]]; then
        stderr "Source directory does not exist!"
        usage
        exit 1
      fi

      # TODO Check destination collection exists...somehow

      echo "Submitting job..."
      local log_dir="${source_dir}/.imirror/logs"
      mkdir -p "${log_dir}"
      bsub -q normal \
           -G hgi \
           -M 1000 \
           -R "select[mem>1000] rusage[mem=1000]" \
           -o "${log_dir}/setup.log" -e "${log_dir}/setup.log" \
           -env IPUT_LIMIT,BSUB_LIMIT \
           "${BINARY}" __setup "${source_dir}" "${dest_coll}"
      ;;
  esac
}

main "${@-}"
